language: r
sudo: required
warnings_are_errors: true

os:
  - linux

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

r_binary_packages:
  - Rcpp
  - bigmemory.sri
  - BH
  - devtools

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript --default-packages='utils,stats,methods' -e 'library(covr);coveralls()'
