language: r
sudo: required
warnings_are_errors: true

os:
  - linux
  - osx

r_binary_packages:
  - Rcpp
  - bigmemory.sri
  - BH

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
